import { test, expect } from '@playwright/test';
import { DataBus } from "../../databuss/dataBus";

test('test', async ({ page }) => {
  await page.goto('http://inblrbnc706.india.tcs.com:22420/branchportal/Main.action#!');
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER531');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByTitle('Click to open drawer').getByLabel('Click to open drawer').click();
  await page.getByRole('listitem', { name: 'Select Customer' }).locator('i').click();
  await page.getByLabel('Service Mode').selectOption('99');
  await page.getByRole('textbox', { name: 'Customer Reference' }).click();
  await page.getByRole('textbox', { name: 'Customer Reference' }).fill('100105677');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('100105677').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Term Account Services').first().click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('.fa.fa-navicon').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('.fa.fa-navicon').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('.fa.fa-navicon').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Open Term Deposit').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#loader').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Deposit Amount' }).fill('100000');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Period', exact: true }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Deposit Amount' }).fill('1000001');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Period', exact: true }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Period', exact: true }).fill('1');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#dep_prodsel_r_termBasis1').selectOption('4');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#dep_prodsel_r_ProductListTable_checkBoxRow_productListTable1').check();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Proceed' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Click to select Source Account').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference', exact: true }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference', exact: true }).fill('R0167000182');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#acnt_accountsListQBE_l_selectProductRow_accountsListTable1').check();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Select' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Auto Renewal').check();
  await expect(page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('alert')).toContainText('Default Settlement Instruction changed');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Principal Only').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Upload Documents').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('.fa.fa-navicon').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByLabel('Upload Documents').getByTitle('Upload Documents').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Upload File  *' }).setInputFiles('data/BSF_CTD_REP_01_OUT_GBANKBSFOU_20260513_124108_36517.pdf');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Upload', exact: true }).click();
  await expect(page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('alert')).toContainText('1064: File is uploaded successfully');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Close' }).click();
  const depositReference = await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#dep_confirmationPage_c_depositReference').textContent();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Release' }).click();
  const fullMessage = await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByLabel('Alerts').getByRole('list').textContent();
  const trans = fullMessage?.trim().split(' ').at(-1)?.replace('.', '');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Pool').check();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('alert')).toContainText('BCF0041: Transaction with the reference number 551~14979 has been sent for authorization.');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('.fa.fa-sign-out').click();
  await expect(page.getByRole('alert')).toContainText('Are you sure you want to logout?');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER530');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('a').filter({ hasText: 'Authorization Queues' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).fill('551~14979');
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#div-inlineSearch')).toContainText('use trans');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('link', { name: 'Pool Queue' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByText('~14979').click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#exception_SelectRow_ejViewExceptionDetailsTable1').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByTitle('Approve').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('alert')).toContainText('BCF0106: New exception(s) raised on this transaction reference 551~14979.');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('.fa.fa-sign-out').click();
  await expect(page.getByRole('alert')).toContainText('Are you sure you want to logout?');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER139');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('a').filter({ hasText: 'Authorization Queues' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).fill('551~14979');
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#div-inlineSearch')).toContainText('use trans');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('link', { name: 'Pool Queue' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByText('~14979').click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#exception_SelectRow_ejViewExceptionDetailsTable2').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByTitle('Approve').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('alert')).toContainText('BCF0038: Transaction with reference 551~14979 is approved.');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('#logoutAnchor').click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER531');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByTitle('Click to open drawer').getByLabel('Click to open drawer').click();
  await page.getByRole('listitem', { name: 'Select Customer' }).locator('i').click();
  await page.getByLabel('Service Mode').selectOption('99');
  await page.getByRole('textbox', { name: 'Customer Reference' }).click();
  await page.getByRole('textbox', { name: 'Customer Reference' }).fill('100105677');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('100105677').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Term Account Services').first().click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference' }).fill('R0167025014');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Actions').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Principal Renewal').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#loader').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Principal Change' }).fill('-1000');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#loader').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('div:nth-child(45) > #div-panel-body-section-2 > #div-3').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  const trans2 = await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('alert').textContent();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Pool').check();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('alert')).toContainText('BCF0041: Transaction with the reference number 551~14979~6 has been sent for authorization.');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('.fa.fa-sign-out').click();
  await expect(page.getByRole('alert')).toContainText('Are you sure you want to logout?');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER530');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('a').filter({ hasText: 'Authorization Queues' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).fill('551~14979~6');
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#div-inlineSearch')).toContainText('use trans');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('link', { name: 'Pool Queue' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByText('~14979~6').click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#exception_SelectRow_ejViewExceptionDetailsTable1').check();
  await page.getByLabel('close notification list').click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByTitle('Approve').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('alert')).toContainText('BCF0106: New exception(s) raised on this transaction reference 551~14979~6.');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('.fa.fa-sign-out').click();
  await expect(page.getByRole('alert')).toContainText('Are you sure you want to logout?');
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER139');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('a').filter({ hasText: 'Authorization Queues' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('textbox', { name: 'Quick Search' }).fill('551~14979~6');
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#div-inlineSearch')).toContainText('use trans');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('link', { name: 'Pool Queue' }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#div-tblId_myQueue div').filter({ hasText: /^Showing: 10 rows20 rows30 rows$/ }).click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByText('~14979~6').click();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().locator('#exception_SelectRow_ejViewExceptionDetailsTable1').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByTitle('Approve').check();
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'Submit' }).click();
  await expect(page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('alert')).toContainText('BCF0038: Transaction with reference 551~14979~6 is approved.');
  await page.locator('iframe[name="frame-1-2"]').contentFrame().getByRole('button', { name: 'OK' }).click();
  await page.locator('.fa.fa-sign-out').click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER531');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Changepwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('USER531');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('ChangePwd@123');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByTitle('Click to open drawer').getByLabel('Click to open drawer').click();
  await page.getByRole('listitem', { name: 'Select Customer' }).locator('i').click();
  await page.getByLabel('Service Mode').selectOption('99');
  await page.getByRole('textbox', { name: 'Customer Reference' }).click();
  await page.getByRole('textbox', { name: 'Customer Reference' }).fill('100105677');
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByText('100105677').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByTitle('Term Account Services').first().click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('textbox', { name: 'Account Reference' }).fill('R0167025014');
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByRole('button', { name: 'Search' }).click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('R0167025014').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('Deal Event').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().getByText('SAR -').click();
  await page.locator('iframe[name="frame-100105677-100105677-5"]').contentFrame().locator('#home').click();
  await page.locator('#logoutAnchor').click();
  await expect(page.getByRole('alert')).toContainText('Are you sure you want to logout?');
  await page.getByRole('button', { name: 'OK' }).click();
});